apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-all-deployment
spec:
  selector:
    matchLabels:
      app:  webapp-all
  replicas: 1 #tells deployment to run on 1 pods
  template:  #create pods using pod definition 
    metadata:
      labels:
        app: webapp-all
    spec:
      containers:
      - name: webapp-all
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: webapp-all-service 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP 
    targetPort: 80
  selector:
    app: webapp-all

