apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-probe 
spec:
  selector:
    matchLabels:
      app: marhaba
  replicas: 1 # creates 1 pods matching the template 
  template: #create pods using pod definition in this template 
      metadata:
        labels:
          app: marhaba
      spec:
        containers:
          - name: marhaba
            image: nginx:1.17.1-alpine
            ports:
            - containerPort: 80
            readinessProbe: #checks when the container is ready to start accepting traffic 
            #length of the time to wait for a pod to initialize
            # after the pod starts up, before applying health checking 
              initialDelaySeconds: 30
            #Amount of time to wait before timing out 
              timeoutSeconds: 1
            # probe for http 
              httpGet: 
              #Path to probe 
                path: /
              #port to probe 
                port: 80
            livenessProbe: #periodic check to make sure the container is healthy
            #length of time to wait before checking liveness
            # after pod startup, before applying health checking 
              initialDelaySeconds: 120
            #  amount of time to wait before timing out 
              timeoutSeconds: 5
            #probe for http 
              httpGet:
              #path to probe 
                path: /
              #port to probe 
                port: 80

