apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-roof-deploy
spec:
  selector:
    matchLabels:
      app:  catroof-all
  replicas: 3 #tells deployment to run on 3 pods
  template:  #create pods using pod definition 
    metadata:
      labels:
        app: catroof-all
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service 
metadata:
  name: cat-roof-service 
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP 
    targetPort: 8080
  selector:
    app: catroof-all

