apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-bootstrap-deploy
spec:
  selector:
    matchLabels:
      app: marhaba 
  replicas: 3 # creates 3 pods matching the template 
  template: # create pods using the pod definition in the template 
    metadata:
      labels:
        app: marhaba
    spec:
      containers:
      - name: marhaba
        image: syedawase/prime-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prime-bootstrap-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:  marhaba 

    